"""empty message

Revision ID: 635543ea7195
Revises: 
Create Date: 2023-08-25 14:53:19.871175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '635543ea7195'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user_studygroup',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('studygroup_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['studygroup_id'], ['study_group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_studygroup')
    op.drop_table('user')
    op.drop_table('study_group')
    # ### end Alembic commands ###
